/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.11.1.0 (NJsonSchema v10.4.3.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class WebsiteClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    /**
     * @return Success
     */
    website(): Observable<WebsiteDto> {
        let url_ = this.baseUrl + "/v1/Website";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processWebsite(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processWebsite(<any>response_);
                } catch (e) {
                    return <Observable<WebsiteDto>><any>_observableThrow(e);
                }
            } else
                return <Observable<WebsiteDto>><any>_observableThrow(response_);
        }));
    }

    protected processWebsite(response: HttpResponseBase): Observable<WebsiteDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = WebsiteDto.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<WebsiteDto>(<any>null);
    }
}

export class TextItem implements ITextItem {
    xPosition?: number;
    yPosition?: number;
    height?: number;
    width?: number;
    text?: string | undefined;
    textSize?: number;

    constructor(data?: ITextItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.xPosition = _data["xPosition"];
            this.yPosition = _data["yPosition"];
            this.height = _data["height"];
            this.width = _data["width"];
            this.text = _data["text"];
            this.textSize = _data["textSize"];
        }
    }

    static fromJS(data: any): TextItem {
        data = typeof data === 'object' ? data : {};
        let result = new TextItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["xPosition"] = this.xPosition;
        data["yPosition"] = this.yPosition;
        data["height"] = this.height;
        data["width"] = this.width;
        data["text"] = this.text;
        data["textSize"] = this.textSize;
        return data; 
    }
}

export interface ITextItem {
    xPosition?: number;
    yPosition?: number;
    height?: number;
    width?: number;
    text?: string | undefined;
    textSize?: number;
}

export class ButtonItem implements IButtonItem {
    xPosition?: number;
    yPosition?: number;
    height?: number;
    width?: number;
    text?: string | undefined;
    textSize?: number;

    constructor(data?: IButtonItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.xPosition = _data["xPosition"];
            this.yPosition = _data["yPosition"];
            this.height = _data["height"];
            this.width = _data["width"];
            this.text = _data["text"];
            this.textSize = _data["textSize"];
        }
    }

    static fromJS(data: any): ButtonItem {
        data = typeof data === 'object' ? data : {};
        let result = new ButtonItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["xPosition"] = this.xPosition;
        data["yPosition"] = this.yPosition;
        data["height"] = this.height;
        data["width"] = this.width;
        data["text"] = this.text;
        data["textSize"] = this.textSize;
        return data; 
    }
}

export interface IButtonItem {
    xPosition?: number;
    yPosition?: number;
    height?: number;
    width?: number;
    text?: string | undefined;
    textSize?: number;
}

export class WebsiteDto implements IWebsiteDto {
    backgroundColor?: string | undefined;
    textItems?: TextItem[] | undefined;
    buttonItems?: ButtonItem[] | undefined;

    constructor(data?: IWebsiteDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.backgroundColor = _data["backgroundColor"];
            if (Array.isArray(_data["textItems"])) {
                this.textItems = [] as any;
                for (let item of _data["textItems"])
                    this.textItems!.push(TextItem.fromJS(item));
            }
            if (Array.isArray(_data["buttonItems"])) {
                this.buttonItems = [] as any;
                for (let item of _data["buttonItems"])
                    this.buttonItems!.push(ButtonItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): WebsiteDto {
        data = typeof data === 'object' ? data : {};
        let result = new WebsiteDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["backgroundColor"] = this.backgroundColor;
        if (Array.isArray(this.textItems)) {
            data["textItems"] = [];
            for (let item of this.textItems)
                data["textItems"].push(item.toJSON());
        }
        if (Array.isArray(this.buttonItems)) {
            data["buttonItems"] = [];
            for (let item of this.buttonItems)
                data["buttonItems"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IWebsiteDto {
    backgroundColor?: string | undefined;
    textItems?: TextItem[] | undefined;
    buttonItems?: ButtonItem[] | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}